version: "3.2"
services:
    synapse:
        build: .
        volumes:
            - type: bind
              source: $PWD/shared
              target: /home/synapse/shared
            - ~/.ssh:/home/synapse/.ssh:ro
        tty: true
