version: "3.2"
services:
    maestro:
        build: .
        image: maestro
        volumes:
            - type: bind
              source: ./shared
              target: /shared
            - type: bind
              source: ~/.gitconfig
              target: /home/snap/.gitconfig
              read_only: true
            - type: bind
              source: ~/.ssh
              target: /home/snap/.ssh
              read_only: true
            - ~/.Xauthority:/home/snap/.Xauthority
        environment:
            DISPLAY: $DISPLAY
        network_mode: "host"
        tty: true
        privileged: true
