version: "3.2"
services:
    snap:
        build: .
        image: snap
        tty: true
        privileged: true

    vigor:
        build:
            context: .
            dockerfile: Dockerfile.vigor
        image: vigor
        volumes:
            - type: bind
              source: ./shared
              target: /home/snap/.shared
            - type: bind
              source: ~/.ssh
              target: /home/snap/.ssh
              read_only: true
        tty: true
        privileged: true

    synapse:
        build:
            context: .
            dockerfile: Dockerfile.synapse
        image: synapse
        volumes:
            - type: bind
              source: ./shared
              target: /home/snap/.shared
            - type: bind
              source: ~/.ssh
              target: /home/snap/.ssh
              read_only: true
        tty: true
        privileged: true