version: "3.2"
services:
    synapse:
        build: .
        volumes:
            - type: bind
              source: ./shared
              target: /home/synapse/.shared
            - type: bind
              source: ~/.ssh
              target: /home/synapse/.ssh
              read_only: true
            - type: bind
              source: /mnt/hugepages2M
              target: /mnt/hugepages2M
        tty: true
        privileged: true